Firs commit
Memonagi/go_final_project pull request #1
Opened 2024-07-02 11:29 UTC by Memonagi

2024-07-10 08:51 UTC, just-musha commented
@Memonagi привет! Подскажи, у тебя тесты все проходят?

2024-07-10 08:53 UTC, just-musha commented
[final-sprint-tests-Memonagi.log](https://github.com/user-attachments/files/16158246/final-sprint-tests-Memonagi.log)

Запустила по инструкции, много упало - можешь проверить у себя, на чистом репозитории?

2024-07-10 09:47 UTC, Memonagi commented
Привет! Локально да, все тесты проходят. 
Только тесты для проверки правила повторения по месяцам я закомментила, так как это условие не проверяла.
Сейчас попробую разобраться, в чем проблема..

2024-07-10 09:53 UTC, Memonagi commented
@just-musha подскажи, пожалуйста, что подразумевается под проверкой на чистом репозитории?

2024-07-10 12:59 UTC, Memonagi commented
@just-musha я поняла ошибку. По какой-то причине у меня  тесты брались из кеша. В PR есть коммит от 04.07.2024, где все тесты работают. Видимо, с тех пор они и кешировались... 
Сейчас проверила, действительно половина тестов сбоит :( Я постараюсь исправить в ближайшее время и снова отправить на ревью.

2024-07-10 14:16 UTC, Memonagi commented
Исправила, все тесты проходят.

2024-07-10 19:03 UTC, just-musha commented
@Memonagi Отлично, спасибо! Завтра посмотрю по коду. 

Про чистый репозиторий - просто заново у себя склонировать свой репозиторий и попробовать прогнать тесты. Бывает что остались локальные изменения и с ними проходит, а закомичено другое, например

2024-07-11 12:35 UTC, just-musha requested changes
Хорошая работа! Отмечу структуру кода - грамотное разделение на слои, пакеты. 
По коду в комментариях ещё отписала что понравилось в использованных решениях

Отправляю правки - в основном по код стайлу и содержимомоу репозитория.

2024-07-11 12:35 UTC, just-musha commented on tests/task_6_test.go
> -	body, err := requestJSON("api/service", nil, http.MethodGet)
Почему меняешь? Тесты не предполагается менять

2024-07-11 12:35 UTC, just-musha commented on .DS_Store
Служебный файл не нужен в репозитории

2024-07-11 12:35 UTC, just-musha commented on .idea/.gitignore
Настройки IDE тоже не нужны в репозитории (`.idea`)

2024-07-11 12:35 UTC, just-musha commented on internal/models/.DS_Store
Тоже не нужен

2024-07-11 12:35 UTC, just-musha commented on dockerfile
```diff
-dockerfile
+Dockerfile
```

2024-07-11 12:35 UTC, just-musha commented on dockerfile
> +FROM debian:stable-slim
Круто что оптимизируешь размер образа :+1:

2024-07-11 12:35 UTC, just-musha commented on internal/models/models.go
> +const (
Константы лучше перенести поближе к месту, где они используются, можно в тот же файл

2024-07-11 12:35 UTC, just-musha commented on tests/nextdate_3_test.go
> +		// {"20231106", "m 13", "20240213"},
Тест кейсы нужно вернуть. Не предполагается менять тесты. Если видишь проблему в тестах - напиши о ней наставнику в общий чат

2024-07-11 12:35 UTC, just-musha commented on web/.DS_Store
Тоже лишний файл в репозитории

2024-07-11 12:35 UTC, just-musha commented on Makefile
Пожелание по оформлению. Если добавляешь Makefile, то было бы хорошо описать как импользоваться, что для него поставить и тд. 
Это не обязательно для принятия работы

2024-07-11 12:35 UTC, just-musha commented on README.md
> +# Описание проекта:
:+1: Четкое понятное описание

2024-07-11 12:35 UTC, just-musha commented on internal/service/service.go
> +	db *database.DB
Хорошо что разделяешь логику на компоненты как это принято в Go

2024-07-11 12:35 UTC, just-musha commented on internal/database/database.go
> +func New(ctx context.Context, dbFile string) (*DB, error) {
```diff
-New
+NewDB
```

2024-07-11 12:35 UTC, just-musha commented on internal/database/database.go
> +	"github.com/Memonagi/go_final_project/internal/models"
Импорты нужно разбить на блоки - сначала стардарные, потом внешние, потом внутренние пакеты

2024-07-11 12:35 UTC, just-musha commented on internal/database/database.go
> +	"github.com/Memonagi/go_final_project/internal/models"
Это нужно пройтись по всем файлам и проверить

2024-07-11 12:35 UTC, just-musha commented on internal/database/database.go
> +		return "", fmt.Errorf("ошибка добавления задачи в БД: %w", err)
Здорово что оборачиваешь ошибки и прокидываешь контекст :+1:

2024-07-11 12:35 UTC, just-musha commented on .golangci.yml
Оч круто что используешь внешний линтер

2024-07-11 12:35 UTC, just-musha commented on cmd/scheduler-service/main.go
> +		dbFile = "scheduler.db"
Тоже лучше в константу вынести наверх дефолтное значение

2024-07-11 12:35 UTC, just-musha commented on internal/date/date.go
> +	if err != nil || days < 1 || days > 400 {
Можно числа повыносить в  константы, чтобы не оставались как magic number  в коде

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +		ctxGf, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Этот таймаут не нужно тоже вынести в константу?

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +const timeout = 5 * time.Second
Если выносишь из функции - назови более конкретно переменную, что это за таймаут

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +		ctxGf, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Что такое `Gf` ? мб переименовать чтобы более понятно было

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +		http.Error(w, fmt.Errorf("error: %w", err).Error(), http.StatusInternalServerError)
Тут достаточно просто залогировать

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +
Лишняя строчка

2024-07-11 12:35 UTC, just-musha commented on internal/handler/handler.go
> +
Тоже лишняя строчка, и в других местах - строчка перед return не нужна

2024-07-11 12:35 UTC, just-musha commented on internal/date/date.go
> +package date
:+1: хорошая идея вынести в отдельный пакет эту часть

2024-07-11 14:49 UTC, Memonagi commented on tests/task_6_test.go
> -	body, err := requestJSON("api/service", nil, http.MethodGet)
Ранее в моем проекте папка "service" называлась "task". Когда я проводила рефакторинг, IDE во всех файлах  проекта заменила слово task на service, а я это не сразу заметила. Пришлось внести правки, чтобы вернуть файл к исходному содержанию

2024-07-11 14:53 UTC, Memonagi commented on internal/handler/handler.go
> +
Я делала проверку golangci-lint, он не принимал return без пустой строки, считал за ошибку. Мне исправить данный пункт во всем коде?

2024-07-11 15:21 UTC, Memonagi commented on tests/nextdate_3_test.go
> +		// {"20231106", "m 13", "20240213"},
Вернула. Данные тесты у меня не пройдут, так как я не сделала проверку на правило повторения "m" (задание со звездочкой)

2024-07-11 16:42 UTC, Memonagi commented
Внесла правки в соответствии с комментариями. Остался только вопрос по пустой строке перед return. Данное исправление мне диктовал линтер. Нужно ли мне редактировать весь код? Просто у меня в каждом файле эти пустые строки есть

2024-07-11 20:57 UTC, just-musha commented on tests/task_6_test.go
> -	body, err := requestJSON("api/service", nil, http.MethodGet)
Поняла, спасибо!

2024-07-11 20:58 UTC, just-musha commented on tests/nextdate_3_test.go
> +		// {"20231106", "m 13", "20240213"},
Поняла, ок!

2024-07-11 21:04 UTC, just-musha commented on internal/handler/handler.go
> +
Выглядит странно просто. Если это линтер так хочет, то ок. Не нужно исправлять

Интересно, что это за проверка/правило, которое это требует. Go lint стандартный такое кажется не просит.

2024-07-11 21:05 UTC, just-musha commented
@Memonagi нет, тогда не нужно исправлять, раз ты используешь этот линтер в своем проекте.

Было бы здорово узнать, что это за правило, которое это требует.

2024-07-11 21:33 UTC, just-musha approved these changes
@Memonagi поздравляю! Финальное задание принято!

Получился хороший, легко поддерживаемый сервис, go way. Спасибо за твою работу, готовность разобраться и быстро внести правки.

Успехов дальше в применении Go для решения своих задач!

2024-07-12 08:06 UTC, Memonagi commented
> @Memonagi нет, тогда не нужно исправлять, раз ты используешь этот линтер в своем проекте.
> 
> Было бы здорово узнать, что это за правило, которое это требует.

Правило nlreturn

2024-07-12 08:07 UTC, Memonagi commented
> @Memonagi поздравляю! Финальное задание принято!
> 
> Получился хороший, легко поддерживаемый сервис, go way. Спасибо за твою работу, готовность разобраться и быстро внести правки.
> 
> Успехов дальше в применении Go для решения своих задач!

Огромное спасибо за твое ревью! Все комментарии были четкие и понятные :)

2024-07-12 08:10 UTC, merged